export const marcasVeiculos = [
  "Abarth",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Bugatti",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroën",
  "Dacia",
  "Daewoo",
  "Daihatsu",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "Honda",
  "Hummer",
  "Hyundai",
  "Infiniti",
  "Isuzu",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lancia",
  "Land Rover",
  "Lexus",
  "Lotus",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MG",
  "Mini",
  "Mitsubishi",
  "Nissan",
  "Opel",
  "Peugeot",
  "Porsche",
  "Renault",
  "Rolls-Royce",
  "Rover",
  "Saab",
  "Seat",
  "Skoda",
  "Smart",
  "SsangYong",
  "Subaru",
  "Suzuki",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

// Gerar lista de anos (de 1950 até o ano atual + 1)
const anoAtual = new Date().getFullYear();
export const anosDisponiveis = Array.from(
  { length: anoAtual - 1949 + 1 },
  (_, i) => anoAtual + 1 - i
);

export const modelosPorMarca: Record<string, string[]> = {
  "Abarth": ["124 Spider", "500", "595", "695"],
  "Alfa Romeo": ["MiTo", "Giulietta", "Giulia", "Stelvio", "Tonale", "4C", "Brera", "159", "147", "156"],
  "Aston Martin": ["Vantage", "DB9", "DB11", "DBS", "DBX", "Rapide", "Vanquish"],
  "Audi": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "TT", "R8", "e-tron", "RS3", "RS4", "RS5", "RS6", "RS7", "S3", "S4", "S5", "S6", "S7", "S8"],
  "Bentley": ["Continental GT", "Continental Flying Spur", "Bentayga", "Mulsanne", "Flying Spur"],
  "BMW": ["Série 1", "Série 2", "Série 3", "Série 4", "Série 5", "Série 6", "Série 7", "Série 8", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z3", "Z4", "i3", "i4", "i7", "i8", "iX", "iX3", "M2", "M3", "M4", "M5", "M6", "M8", "X5 M", "X6 M"],
  "Bugatti": ["Veyron", "Chiron", "Divo", "Centodieci"],
  "Cadillac": ["ATS", "CTS", "CT6", "Escalade", "XT4", "XT5", "XT6"],
  "Chevrolet": ["Spark", "Aveo", "Cruze", "Malibu", "Camaro", "Corvette", "Trax", "Equinox", "Traverse", "Tahoe", "Suburban", "Silverado"],
  "Chrysler": ["300", "Pacifica", "Voyager"],
  "Citroën": ["C1", "C3", "C3 Aircross", "C4", "C4 Cactus", "C5", "C5 Aircross", "C5 X", "Berlingo", "SpaceTourer", "Jumpy", "DS3", "DS4", "DS5"],
  "Dacia": ["Sandero", "Sandero Stepway", "Logan", "Duster", "Jogger", "Spring", "Lodgy"],
  "Daewoo": ["Matiz", "Kalos", "Lacetti", "Nubira", "Leganza"],
  "Daihatsu": ["Cuore", "Sirion", "Terios", "Copen"],
  "Dodge": ["Challenger", "Charger", "Durango", "Journey", "Ram"],
  "Ferrari": ["Roma", "Portofino", "F8 Tributo", "F8 Spider", "SF90 Stradale", "812 Superfast", "296 GTB", "Purosangue", "488", "458", "California", "FF", "GTC4Lusso"],
  "Fiat": ["500", "500X", "500L", "Panda", "Tipo", "Punto", "Bravo", "Doblo", "Ducato", "Freemont", "Multipla", "Stilo", "Uno"],
  "Ford": ["Fiesta", "Focus", "Mondeo", "Mustang", "Kuga", "Puma", "EcoSport", "Edge", "Explorer", "Ranger", "Transit", "S-Max", "Galaxy", "C-Max", "B-Max", "Ka"],
  "Honda": ["Jazz", "Civic", "Accord", "CR-V", "HR-V", "e", "NSX", "Insight", "Pilot", "Odyssey"],
  "Hummer": ["H1", "H2", "H3"],
  "Hyundai": ["i10", "i20", "i30", "i40", "Tucson", "Santa Fe", "Kona", "Bayon", "Ioniq", "Ioniq 5", "Ioniq 6", "Nexo", "Veloster", "Genesis"],
  "Infiniti": ["Q30", "Q50", "Q60", "Q70", "QX30", "QX50", "QX60", "QX70", "QX80"],
  "Isuzu": ["D-Max", "MU-X"],
  "Jaguar": ["XE", "XF", "XJ", "F-Type", "F-Pace", "E-Pace", "I-Pace"],
  "Jeep": ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler", "Gladiator", "Wagoneer"],
  "Kia": ["Picanto", "Rio", "Ceed", "Proceed", "Stonic", "XCeed", "Sportage", "Sorento", "Niro", "e-Niro", "EV6", "EV9", "Soul", "Optima", "Stinger"],
  "Lancia": ["Ypsilon", "Delta", "Musa", "Thesis"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Sport", "Range Rover Evoque", "Range Rover Velar", "Freelander"],
  "Lexus": ["CT", "IS", "ES", "GS", "LS", "RC", "LC", "UX", "NX", "RX", "GX", "LX"],
  "Lotus": ["Elise", "Exige", "Evora", "Emira"],
  "Maserati": ["Ghibli", "Quattroporte", "Levante", "MC20", "Grecale", "GranTurismo", "GranCabrio"],
  "Mazda": ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-30", "CX-5", "CX-60", "CX-9", "MX-5", "MX-30", "RX-8"],
  "McLaren": ["540C", "570S", "600LT", "720S", "765LT", "Artura", "GT"],
  "Mercedes-Benz": ["Classe A", "Classe B", "Classe C", "Classe E", "Classe S", "CLA", "CLS", "GLA", "GLB", "GLC", "GLE", "GLS", "Classe G", "EQA", "EQB", "EQC", "EQE", "EQS", "EQV", "AMG GT", "SL", "SLC", "Vito", "Sprinter"],
  "MG": ["MG3", "MG4", "MG5", "ZS", "HS", "Marvel R"],
  "Mini": ["Cooper", "Cooper S", "Cooper D", "Countryman", "Clubman", "Paceman", "Electric", "John Cooper Works"],
  "Mitsubishi": ["Space Star", "Mirage", "ASX", "Eclipse Cross", "Outlander", "Pajero", "L200"],
  "Nissan": ["Micra", "Note", "Juke", "Qashqai", "X-Trail", "Leaf", "Ariya", "GT-R", "370Z", "Navara", "Pathfinder", "Murano", "Pulsar"],
  "Opel": ["Corsa", "Astra", "Insignia", "Crossland", "Grandland", "Mokka", "Combo", "Vivaro", "Zafira", "Adam", "Karl", "Meriva"],
  "Peugeot": ["108", "208", "308", "508", "2008", "3008", "5008", "Rifter", "Partner", "Traveller", "e-208", "e-2008", "RCZ", "207", "307", "407"],
  "Porsche": ["911", "718 Cayman", "718 Boxster", "Panamera", "Cayenne", "Macan", "Taycan", "918 Spyder"],
  "Renault": ["Twingo", "Clio", "Captur", "Megane", "Kadjar", "Koleos", "Scenic", "Talisman", "Zoe", "Kangoo", "Trafic", "Master", "Espace", "Laguna"],
  "Rolls-Royce": ["Ghost", "Phantom", "Cullinan", "Wraith", "Dawn", "Silver Shadow"],
  "Rover": ["25", "45", "75", "Streetwise"],
  "Saab": ["9-3", "9-5"],
  "Seat": ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco", "Alhambra", "Mii", "Toledo", "Altea"],
  "Skoda": ["Citigo", "Fabia", "Scala", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Enyaq", "Yeti", "Rapid"],
  "Smart": ["Fortwo", "Forfour", "Roadster"],
  "SsangYong": ["Tivoli", "Korando", "Rexton", "Musso"],
  "Subaru": ["Impreza", "XV", "Forester", "Outback", "Legacy", "BRZ", "WRX"],
  "Suzuki": ["Celerio", "Swift", "Ignis", "Baleno", "Vitara", "S-Cross", "Jimny", "Across", "Swace"],
  "Tesla": ["Model S", "Model 3", "Model X", "Model Y", "Roadster", "Cybertruck"],
  "Toyota": ["Aygo", "Yaris", "Corolla", "Camry", "Prius", "C-HR", "RAV4", "Highlander", "Land Cruiser", "Hilux", "Proace", "bZ4X", "Supra", "GT86", "Avensis", "Auris"],
  "Volkswagen": ["Up!", "Polo", "Golf", "Passat", "Arteon", "Tiguan", "Touareg", "T-Cross", "T-Roc", "Touran", "Sharan", "Caddy", "Transporter", "ID.3", "ID.4", "ID.5", "ID.Buzz", "Beetle", "Scirocco", "Jetta"],
  "Volvo": ["V40", "V60", "V90", "S60", "S90", "XC40", "XC60", "XC90", "C40", "EX30", "EX90", "C30", "C70"],
};
